trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo 'Hello, Azure Pipelines!'
  displayName: 'Print a message'
- script: echo 'This is a simple pipeline.'
  displayName: 'Print another message'
